version: '3.7'

services:
  db:
    image: "postgres:10"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web: 
    build:
      context: .
      dockerfile: web.dockerfile
    command: python Pytreddit/manage.py runserver 0.0.0.0:8000
    env_file: 
      - psql.env
      - redis.env
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  