# Generated by Django 3.1.4 on 2020-12-09 13:24

import django.contrib.postgres.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="picture_path",
        ),
        migrations.AddField(
            model_name="forum",
            name="photo",
            field=models.ImageField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/media/photos"
                ),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="contents",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="letter",
            name="contents_files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FileField(
                    blank=True,
                    null=True,
                    storage=django.core.files.storage.FileSystemStorage(
                        location="/media/photos"
                    ),
                    upload_to="",
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="reply_to",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emails.letter",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="subject",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forum",
            name="description",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="ForumMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=1000)),
                ("contents", models.TextField()),
                (
                    "contents_files",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FileField(
                            blank=True,
                            null=True,
                            storage=django.core.files.storage.FileSystemStorage(
                                location="/media/photos"
                            ),
                            upload_to="",
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "to_forum",
                    models.ManyToManyField(
                        blank=True, default=list, to="emails.Forum"
                    ),
                ),
            ],
        ),
    ]
