# Generated by Django 3.1.4 on 2020-12-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20201211_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_user',
            field=models.CharField(max_length=200),
        ),
    ]
