# Generated by Django 3.1.4 on 2020-12-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20201211_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='contents_files',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='forummessage',
            name='contents_files',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
