# Generated by Django 3.1.4 on 2020-12-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20201211_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forummessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='forummessage',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='forummessage',
            name='to_forum',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='ForumMessage',
        ),
    ]
