# Generated by Django 3.1.4 on 2020-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_picture_path",
            new_name="profile_picture_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
