# Generated by Django 3.1.4 on 2020-12-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20201209_1009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_stuff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="login",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
