# Generated by Django 3.1.4 on 2020-12-10 17:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201209_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_email_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
            preserve_default=False,
        ),
    ]
