# Generated by Django 3.1.4 on 2020-12-10 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_my_email_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_email_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
