# Generated by Django 3.1.4 on 2020-12-11 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_emails_sent_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emails_sent_by_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_email_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
    ]
